dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.2.1

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.2.1"
dotenv: .env
wallet:
  from_key: ${PRIVATE_KEY}
networks:
  sepolia:
    eth_use_rice_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
  mainnet-fork-dev:
    eth_use_rice_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"
